apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: java-app-dev
spec:
  project: default
  source:
    repoURL: 'https://github.com/hassan308/IAC.git'
    path: charts/java-app
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml  # Standard värden fil som finns i chart katalogen
        - environments/dev/values.yaml  # Miljöspecifik values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
