# applications/dev/java-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: java-app-dev
spec:
  project: default
  source:
    repoURL: 'https://github.com/hassan308/IAC.git'
    path: charts/myapp
    targetRevision: HEAD
    helm:
      valueFiles:
        - environments/dev/values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
